void binaryRadixSort(int array[], int length);
void binaryInsertionSort(int array[], int length);
int bogoSort(int array[], int length);
void bubbleSort(int array[], int length);
void countingSort(int array[], int length);
void decimalRadixSort(int array[], int length);
void threadedMergeSort(int array[], int length);
void heapsort(int array[], int length);
void hexidecimalRadixSort(int array[], int length);
void mergeSort(int array[], int length);
void merge(int *array1, int *array2, int length);
void quicksort(int array[], int length);
void quicksortWithStages(int array[], int length);
void slowsort(int array[], int length);
void stoogeSort(int array[], int length);
